import os
import torch
import torchvision.transforms.functional as TF
from unet_model import UNet
import skimage.io as io
import numpy as np

# Configuration
# Configuration
# Change from raw images to the clean images generated by the DAE
IMAGE_DIR = "clean_images"  
OUTPUT_MASK_DIR = "unet_output"
MODEL_WEIGHTS = "unet_retina.pth"
SIZE = (512, 512)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

def predict():
    # Ensure output directory exists
    os.makedirs(OUTPUT_SEG_DIR, exist_ok=True)
    
    # Initialize and load model
    model = UNet(in_channels=1, out_channels=1).to(DEVICE)
    if not os.path.exists(MODEL_WEIGHTS):
        print(f"Error: Model weights file '{MODEL_WEIGHTS}' not found. Please train the model first.")
        return
        
    model.load_state_dict(torch.load(MODEL_WEIGHTS, map_location=DEVICE))
    model.eval()
    print("Loaded model weights successfully. Starting segmentation...")
    
    images = sorted(os.listdir(TEST_IMAGE_DIR))
    
    with torch.no_grad():
        for fname in images:
            if fname.endswith(('.jpg', '.jpeg', '.png', '.tif')):
                print(f"Segmenting: {fname}")
                img_path = os.path.join(TEST_IMAGE_DIR, fname)
                
                # Read original dimensions to resize back later
                orig_img = io.imread(img_path)
                orig_h, orig_w = orig_img.shape[0], orig_img.shape[1]
                
                # Load as grayscale float
                image = io.imread(img_path, as_gray=True).astype(np.float32)
                image_tensor = torch.tensor(image).unsqueeze(0).unsqueeze(0) # Shape: [1, 1, H, W]
                
                # Resize to model dimensions
                resized_tensor = TF.resize(image_tensor, SIZE).to(DEVICE)
                
                # Run inference
                pred = model(resized_tensor)
                
                # Resize back to original size
                pred_resized = TF.resize(pred, (orig_h, orig_w))
                
                # Move to CPU, remove channel dims, and convert to binary (0 or 255)
                pred_np = pred_resized.squeeze().cpu().numpy()
                binary_mask = (pred_np > 0.5).astype(np.uint8) * 255
                
                # Save the result
                out_path = os.path.join(OUTPUT_SEG_DIR, fname.split('.')[0] + "_mask.jpg")
                io.imsave(out_path, binary_mask, check_contrast=False)
                
    print(f"All segmentations saved successfully to '{OUTPUT_SEG_DIR}'")

if __name__ == "__main__":
    predict()
